import Phaser from "phaser";
import { AssetKeys } from "../data/assets";

/**
 * The project's pixel font, used as a Phaser RetroFont (a texture-based bitmap
 * font) so glyphs scale with nearest-neighbour like the rest of the pixel art
 * — unlike Phaser Text objects, which rasterize at base resolution and blur
 * when upscaled.
 *
 * The atlas (public/assets/font.png) is generated by scripts/gen-font.mjs; the
 * metrics below MUST match that script.
 */

/** bitmapFont cache key used by the text factory (createText). */
export const FONT_KEY = "pixel";

const CELL_W = 6;
const CELL_H = 8;
const CHARS_PER_ROW = 16;
const FIRST_CODE = 32;
const LAST_CODE = 126;

/** Glyph height in source pixels (1px line gap is included in CELL_H). */
export const FONT_SIZE = CELL_H;

/** ASCII 32..126 in atlas (row-major) order. */
const FONT_CHARS = (() => {
  let s = "";
  for (let c = FIRST_CODE; c <= LAST_CODE; c++) s += String.fromCharCode(c);
  return s;
})();

/**
 * Build the RetroFont from the loaded atlas and register it in the (global)
 * bitmap-font cache. Call once after the font image has loaded.
 */
export function registerPixelFont(scene: Phaser.Scene): void {
  if (scene.cache.bitmapFont.has(FONT_KEY)) return;
  const data = Phaser.GameObjects.RetroFont.Parse(scene, {
    image: AssetKeys.FONT,
    width: CELL_W,
    height: CELL_H,
    chars: FONT_CHARS,
    charsPerRow: CHARS_PER_ROW,
    "offset.x": 0,
    "offset.y": 0,
    "spacing.x": 0,
    "spacing.y": 0,
    lineSpacing: 0,
  });
  scene.cache.bitmapFont.add(FONT_KEY, data);
}
